version: '3'

services:
  backend:
    container_name: 'kupipodariday-backend'
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    ports:
      - '4000:3000'
    depends_on:
      - postgres

  postgres:
    container_name: 'kupipodariday-database'
    image: postgres:12.12-alpine
    restart: always
    env_file: .env

  frontend:
    container_name: 'kupipodariday-frontend'
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '81:80'
